
# Numpy Random Package

___




numpy.random package v1.19

***

In this assignment I will be explaining the uses of the numpy.random package. It is a sub package of numpy, numpy can create multi dimensonal arrays and uses algorithms to quickly analyse data. NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.
The numpy.random package is used to generate simulated data which then can be used in an array to carry out analysis.

What is an array
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively. a list of numbers will create a 1D array,a list of lists will create a 2D array,

further nested lists will create higher-dimensional arrays

ref:https://numpy.org/doc/stable/user/basics.creation.html

<br>
Simple random data functions

***

There are four simple random data functions
- integers (low[, high, size, dtype, endpoint])
- Random ([size, dtype, out])
- Choice 
- Bytes


random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)
Return random integers from low (inclusive) to high (exclusive), or if endpoint=True, low (inclusive) to high (inclusive). Replaces RandomState.randint (with endpoint=False) and RandomState.random_integers (with endpoint=True)

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html


In [5]:

#Examples
import numpy as np
import random
rng = np.random.default_rng()

#1
rng.integers(2, size=10)
array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0])  # random


rng.integers(1, size=10)
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


#2Generate a 2 x 4 array of ints between 0 and 4, inclusive:

rng.integers(5, size=(2, 4))
array([[4, 0, 2, 1],
       [3, 2, 2, 0]])  # random


#Generate a 1 x 3 array with 3 different upper bounds

rng.integers(1, [3, 5, 10])
array([2, 2, 9])  # random


#Generate a 1 by 3 array with 3 different lower bounds

rng.integers([1, 5, 7], 10)
array([9, 8, 7])  # random


#Generate a 2 by 4 array using broadcasting with dtype of uint8

rng.integers([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
array([[ 8,  6,  9,  7],
       [ 1, 16,  9, 12]], dtype=uint8)  # random


6


In [2]:
# Integers - returns random integers

#this will return one random integer between 0-5
rng.integers (6)

#this will return 10000 random integers between 0-99
i = rng.integers (100, size =10000)
print ("i", i)
#this will return 5 coloumns and 3 rows of random integers between the numbers 0 - 99
x = rng.integers (100, size = (5  , 3))
print ("x", x)

i [67 38 32 ... 52 93 73]
x [[99 98 24]
 [19 91 67]
 [32  6 69]
 [10 29 37]
 [41 45 33]]


random.Generator.random(size=None, dtype=np.float64, out=None) 
Return random floats in the half-open interval [0.0, 1.0).
Results are from the “continuous uniform” distribution over the stated interval
Parameters
sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

dtypedtype, optional
Desired dtype of the result, only float64 and float32 are supported. Byteorder must be native. The default value is np.float64.

outndarray, optional
Alternative output array in which to place the result. If size is not None, it must have the same shape as the provided size and must match the type of the output values.

Returns
outfloat or ndarray of floats
Array of random floats of shape size (unless size=None, in which case a single float is returned).

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html

In [3]:
#Example
rng = np.random.default_rng()
rng.random()
0.47108547995356098 # random
type(rng.random())
<class 'float'>
rng.random((5,))
array([ 0.30220482,  0.86820401,  0.1654503 ,  0.11659149,  0.54323428]) # random

In [ ]:
# Example
# Three-by-two array of random numbers from [-5, 0):

5 * rng.random((3, 2)) - 5
array([[-3.99149989, -0.52338984], # random
       [-2.99091858, -0.79479508],
       [-1.23204345, -1.75224494]])


Choice - random.Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)¶

***
The choice() method allows you to generate a random value based on an array of values.
The choice() method takes an array as a parameter and randomly returns one of the values.
Return one of the values in an array:

In [8]:

#Example return one of the values in the array
from numpy import random
rng = np.random.default_rng()

rng.choice([3, 5, 7, 9])



7

The choice() method also allows you to return an array of values.

This can be achieved by adding a size parameter to specify the shape of the array.
size{int, tuple[int]}, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn from the 1-d a. If a has more than one dimension, the size shape will be inserted into the axis dimension, so the output ndim will be a.ndim - 1 + len(size). Default is None, in which case a single value is returned.

 

In [9]:
#Example of 2-D array size set to generate 4 rows
# Each row generates 6 values from the array parameter (3, 5, 7, and 9):
from numpy import random
rng = np.random.default_rng()

rng.choice([3, 5, 7, 9], size=(4,6))



#Weights

#Ref https://www.w3schools.com/python/numpy/numpy_random.asp 

array([[5, 7, 9, 7, 7, 9],
       [9, 9, 3, 7, 7, 3],
       [7, 5, 7, 9, 9, 3],
       [9, 3, 5, 5, 3, 9]])


Choice and probabaility density function ( A function that describes a continuous probability. i.e. probability of all values in an array).

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur. 

In the below example - 
The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

The sum of all probability numbers should be 1.

As the example below shows 9 will never occur in the output





In [10]:
#example choice and probabilty density function

from numpy import random
rng = np.random.default_rng()

rng.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))


array([7, 5, 5, 7, 5, 7, 3, 7, 5, 7, 5, 7, 5, 5, 7, 5, 5, 5, 7, 7, 5, 7,
       7, 5, 7, 5, 7, 7, 3, 7, 7, 7, 5, 3, 5, 7, 5, 7, 7, 7, 5, 3, 5, 5,
       7, 7, 7, 7, 7, 5, 7, 7, 5, 7, 7, 7, 7, 5, 5, 7, 7, 7, 7, 7, 5, 7,
       5, 7, 7, 7, 7, 7, 7, 5, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 7, 7,
       7, 3, 5, 7, 7, 7, 5, 5, 3, 7, 7, 5])

In [11]:
#choice also allows you to return arrays of any shape and size by specifing the shape in the size parameter
#below example shows the return of a 2-D array with 3 rows each containing 5 values

from numpy import random
rng = np.random.default_rng()

rng.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))



array([[7, 5, 7, 5, 7],
       [3, 7, 7, 7, 7],
       [7, 5, 7, 5, 7]])

numpy.random.Generator.bytes
Return random bytes.

Parameters
lengthint
Number of random bytes.

Returns
outbytes
String of length length.


In [13]:
#Bytes This function of random module is used to generate random bytes.
#Example
import numpy as np  
np.random.default_rng().bytes(10)


b'S0\xebJ\x88\xc2A"\xeb\xbe'

<br>
Permutations functions - grouping values were the order of values matter

***
There are the following functions of permutations:

1) np.random.shuffle()

This function is used for modifying a sequence in-place by shuffling its contents.

2) np.random.permutation()

This function permute a sequence randomly or return a permuted range.

3) np.random.permuted () 

This function randomly permute x along axis axis.

In [9]:
#Example of np.random.permutation

import numpy as np  
a=np.random.permutation(12)  
a  

array([ 2, 11,  1,  5,  3, 10,  8,  0,  7,  6,  9,  4])

In [10]:
# Example of np.random.permuted

np.permuted(x, axis=1)

AttributeError: module 'numpy' has no attribute 'permuted'

In [11]:
#Example of np.random.shuffle e.g shuffle cards

import numpy as np  
a=np.arange(12)  
a  
np.random.shuffle(a)  
a  

array([ 8,  6,  3,  1,  2,  4,  0, 10,  7, 11,  9,  5])

<br>
Distributions function

***

Explain use - to generate random python data


<br>
Disribution functions

***

Uniform distribution - one of the key distributions

Normal Distribution Function

Gamma Distribution Function

Poisson Distribution

Binomial Distribution


https://www.datacamp.com/community/tutorials/probability-distributions-python

In [ ]:
import matplotlib.pyplot as plt # used to create distribution plots
import seaborn as sns  # used to visualize random distributions

Uniform Distribution

***
random.Generator.uniform(low=0.0, high=1.0, size=None)
Draw samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high). In other words, any value within the given interval is equally likely to be drawn by uniform.

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.uniform.html

In [12]:
#Show uniform distribution of random integers in histogram plot

#Examples

#Draw samples from the distribution:

s = np.random.default_rng().uniform(-1,0,1000)
#All values are within the given interval:

np.all(s >= -1)
True
np.all(s < 0)
True
#Display the histogram of the samples, along with the probability density function:

import matplotlib.pyplot as plt
count, bins, ignored = plt.hist(s, 15, density=True)
plt.plot(bins, np.ones_like(bins), linewidth=2, color='r')
plt.show()


Normal Distribution

***

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first derived by De Moivre and 200 years later by both Gauss and Laplace independently [2], is often called the bell curve because of its characteristic shape (see the example below).

The normal distributions occurs often in nature. For example, it describes the commonly occurring distribution of samples influenced by a large number of tiny, random disturbances, each with its own unique distribution [2].

In [13]:
#Normal distribution
#Examples

#Draw samples from the distribution:

mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.default_rng().normal(mu, sigma, 1000)
#Verify the mean and the variance:

abs(mu - np.mean(s))
0.0  # may vary
abs(sigma - np.std(s, ddof=1))
0.0  # may vary
#Display the histogram of the samples, along with the probability density function:

import matplotlib.pyplot as plt
count, bins, ignored = plt.hist(s, 30, density=True)
plt.plot(bins, 1/(sigma * np.sqrt(2 * np.pi)) *
               np.exp( - (bins - mu)**2 / (2 * sigma**2) ),
         linewidth=2, color='r')
plt.show()


In [14]:
#Multinomial Distribution

Poisson Distribution

***

random.Generator.poisson(lam=1.0, size=None)
Draw samples from a Poisson distribution.

The Poisson distribution is the limit of the binomial distribution for large N.


In [15]:
#Poisson Distribution 
# Examples

#Draw samples from the distribution:

import numpy as np
rng = np.random.default_rng()
s = rng.poisson(5, 10000)

#Display histogram of the sample:

import matplotlib.pyplot as plt
count, bins, ignored = plt.hist(s, 14, density=True)
plt.show()

In [ ]:
#Draw each 100 values for lambda 100 and 500:

s = rng.poisson(lam=(100., 500.), size=(100, 2))

Binomial Distribution

***
random.Generator.binomial(n, p, size=None)
Draw samples from a binomial distribution.

Samples are drawn from a binomial distribution with specified parameters, n trials and p probability of success where n an integer >= 0 and p is in the interval [0,1]. (n may be input as a float, but it is truncated to an integer in use)

When estimating the standard error of a proportion in a population by using a random sample, the normal distribution works well unless the product p*n <=5, where p = population proportion estimate, and n = number of samples, in which case the binomial distribution is used instead. For example, a sample of 15 people shows 4 who are left handed, and 11 who are right handed. Then p = 4/15 = 27%. 0.27*15 = 4, so the binomial distribution should be used in this case.

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.binomial.html


In [14]:
#Binomial Distribution

#Examples

#Draw samples from the distribution:

rng = np.random.default_rng()
n, p = 10, .5  # number of trials, probability of each trial
s = rng.binomial(n, p, 1000)
# result of flipping a coin 10 times, tested 1000 times.


In [15]:
#A real world example. A company drills 9 wild-cat oil exploration wells, each with an estimated probability of success of 0.1. All nine wells fail. What is the probability of that happening?

#Let’s do 20,000 trials of the model, and count the number that generate zero positive results.

sum(rng.binomial(9, 0.1, 20000) == 0)/20000.
# answer = 0.38885, or 39%.

0.3899

<br>
Explain the use of seeds in generating pseudorandon numbers

***
Numpy's random module, a suite of functions based on pseudorandom number generation. Random means something that can not be predicted logically.
The pseudorandom number works by starting with an integer called a seed and then generates numbers in succession. The same seed gives the same sequence of random numbers, hence the name "pseudo" random number generation. If you want to have reproducible code, it is good to seed the random number generator using the np.random.seed() function.

To do the coin flips, you import NumPy, seed the random number generator, and then draw four random numbers. You can specify how many random numbers you want with the size keyword.

In previous version of Numpy random (v1.15) the default random generator used the mersenne twister (MT19937) algorythm. This algorthym not perfect in terms of non-predictability. The MT19937 algorithm keeps track of its state in 624 32-bit values. If an attacker were able to gather 624 sequential values, then the entire sequence—forward and backward—could be reverse-engineered.

In the latest update of Numpy.Random v1.19 The default bitgenerator is now the Permuted Congruential Generator 64 Bit (PCG64). The following website provides an at a glance comparision of the two types of algorythm - https://www.pcg-random.org/. PCG64 improves the statistical performance when random number generating and it is much more randon when compared to mersenne twist which makes it harder to predict its output and therefore more secure.

In [2]:
import random
for i in range(10):
# Any number or integer value can be used instead of using '0'.
  random.seed(0)
# Generation of random values will be between 1 to 100.
print(random.randint(1, 100))

50


In [3]:
import random

# print a random number between 1 and 1000.

# the code is written in order to repeat the same random number multiple times
random.seed(3)
print(random.randint(1000, 8000))


2949


In [4]:
# If seed function is not used
# The program is being used to generate unpridictible output and genrate totally random values
print(random.randint(1000, 8000))

5854


<br>
References

***

https://numpy.org/doc/stable/reference/random/index.html

https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator

https://www.w3schools.com/python/numpy/numpy_random.asp

https://numpy.org/doc/stable/user/basics.creation.html

https://www.datacamp.com/community/tutorials/probability-distributions-python

https://www.javatpoint.com/numpy-random


https://www.w3schools.com/python/numpy/numpy_random_distribution.asp


Seeds

https://www.pcg-random.org/ 

https://www.datacamp.com/community/tutorials/numpy-random

https://www.sciencedirect.com/topics/computer-science/mersenne-twister

https://www.educba.com/numpy-random-seed/