<br>
# Numpy Random Package

___


<br>
numpy.random package v1.19

***

In this assignment I will be explaining the uses of the numpy.random package. It is a sub package of numpy, numpy can create multi dimensonal arrays and uses algorithms to quickly analyse data. NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.
The numpy.random package is used to generate simulated data which then can be used in an array to carry out analysis.

What is an array
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively. a list of numbers will create a 1D array,

a list of lists will create a 2D array,

further nested lists will create higher-dimensional arrays

ref:https://numpy.org/doc/stable/user/basics.creation.html


<br>
Simple random data functions

***

There are four simple random data functions
- integers (low[, high, size, dtype, endpoint])
- Random ([size, dtype, out])
- Choice 
- Bytes


In [1]:
import numpy as np

rng = np.random.default_rng()

In [6]:
# Integers - returns random integers

#this will return one random integer between 0-5
rng.integers (6)

#this will return 10000 random integers between 0-99
i = rng.integers (100, size =10000)
print ("i", i)
#this will return 5 coloumns and 3 rows of random integers between the numbers 0 - 99
x = rng.integers (100, size = (5  , 3))
print ("x", x)

i [13 75 56 ... 55 83 68]
x [[85 98 38]
 [81 12 32]
 [94 46 29]
 [89 12 77]
 [90  5 81]]


In [ ]:
# Random

In [3]:
#Choice 
#The choice() method allows you to generate a random value based on an array of values.
#The choice() method takes an array as a parameter and randomly returns one of the values.
#Return one of the values in an array:
#Example
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

#The choice() method also allows you to return an array of values.

#Add a size parameter to specify the shape of the array.

#Example
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

#Ref https://www.w3schools.com/python/numpy/numpy_random.asp 

5
[[9 7 7 3 7]
 [7 7 5 9 3]
 [9 5 7 7 9]]


In [ ]:
#Bytes

<br>
Permutations functions

***

Explain the use

<br>
Distributions function

***

Explain use - to generate random python data


5 Disribution functions

Uniform distribution - one of the key distributions
Normal Distribution Function
Gamma Distribution Function
Poisson Distribution
Binomial Distribution


https://www.datacamp.com/community/tutorials/probability-distributions-python

In [ ]:
#Show uniform distribution of random integers in histogram plot

import matplotlib.pyplot as plt

plt.hist (i)
plt.show ()

<br>
Explain the use of seeds in generating pseudorandon numbers

***

<br>
References

***

https://numpy.org/doc/stable/reference/random/index.html

https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator

https://www.w3schools.com/python/numpy/numpy_random.asp

https://numpy.org/doc/stable/user/basics.creation.html

https://www.datacamp.com/community/tutorials/probability-distributions-python


